apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronotrack-api-deploy
spec:
  selector:
    matchLabels:
      app: chronotrack-api
  replicas: 1
  template:
    metadata:
      labels:
        app: chronotrack-api
    spec:
      containers:
      - name: app-wise
        image: us.gcr.io/ramon-prd/chronotrack-api:latest
        resources:
          requests:
            cpu: "10m"
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: storage-credentials
            mountPath: /google_application
            readOnly: true
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.14
        resources:
          requests:
            cpu: "10m"
        command: ["/cloud_sql_proxy"]
        args: ["$(InstanceMysql)", "$(KeyMysql)"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: storage-credentials
          secret:
            secretName: storage-credentials
