apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-manager-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ramon-prd
  namespace: default
roleRef:
  kind: Role
  name: service-manager
  apiGroup: rbac.authorization.k8s.io