name: Build and deploy Docker app to Azure Web App - chronotrack-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Login no Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login ${{ secrets.AZURE_ACR_LOGIN_SERVER }} -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Construir e enviar imagem Docker
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/chronotrack-api:latest -f Dockerfile .
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/chronotrack-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Fazer deploy no Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chronotrack-api'
          images: '${{ secrets.AZURE_ACR_LOGIN_SERVER }}/chronotrack-api:latest'
